# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_auto_20160112_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='faculty_t_cv/'),
        ),
    ]
