# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0004_auto_20160112_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='previous_year',
            field=models.CharField(blank=True, choices=[('1', 'FIRST_YEAR'), ('2', 'SECOND_YEAR'), ('3', 'THIRD_YEAR'), ('4', 'FOURTH_YEAR')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='previous_year_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='previous_year_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
