# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0005_auto_20160114_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='previous_year',
            field=models.CharField(blank=True, choices=[('FIRST_YEAR', 'FIRST_YEAR'), ('SECOND_YEAR', 'SECOND_YEAR'), ('THIRD_YEAR', 'THIRD_YEAR'), ('FOURTH_YEAR', 'FOURTH_YEAR')], max_length=20, null=True),
        ),
    ]
