# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0007_auto_20160114_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='previous_year',
            field=models.CharField(blank=True, choices=[('FIRSTYEAR', 'FIRST_YEAR'), ('SECONDYEAR', 'SECOND_YEAR'), ('THIRDYEAR', 'THIRD_YEAR'), ('FOURTHYEAR', 'FOURTH_YEAR')], max_length=20, null=True),
        ),
    ]
