# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0010_auto_20160114_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_table_year',
            field=models.CharField(blank=True, choices=[('FIRSTSEMESTER', 'FIRST_SEMESTER'), ('SECONDSEMESTER', 'SECOND_SEMESTER'), ('THIRDSEMESTER', 'THIRD_SEMESTER'), ('FOURTHSEMESTER', 'FOURTH_SEMESTER'), ('FIFTHSEMESTER', 'FIFTH_SEMESTER'), ('SIXTHSEMESTER', 'SIXTH_SEMESTER'), ('SEVENTHSEMESTER', 'SEVENTH_SEMESTER'), ('EIGHTSEMESTER', 'EIGHT_SEMESTER')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_table_group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
