# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0011_auto_20160114_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='syllabus_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='syllabus_year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
