# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_extended', '0002_auto_20160111_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload',
        ),
    ]
