# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_rec', '0003_remove_post_image_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='companies_logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/placement-rec'),
        ),
        migrations.AlterField(
            model_name='post',
            name='placement_recfile',
            field=models.FileField(blank=True, null=True, upload_to='uploads/placement-rec'),
        ),
    ]
