# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_rec', '0004_auto_20160109_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='companies_logo',
            field=models.ImageField(blank=True, default=None, upload_to='uploads/placement-rec'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='placement_recfile',
            field=models.FileField(blank=True, default=None, upload_to='uploads/placement-rec'),
        ),
        migrations.AlterField(
            model_name='post',
            name='placement_year',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
