# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_rec', '0008_auto_20160110_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='companies_logo',
            field=models.ImageField(upload_to='uploads/placement-rec'),
        ),
    ]
