# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_rec', '0009_auto_20160110_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default=datetime.datetime(2016, 1, 10, 18, 45, 15, 358147, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
