# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 19:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('placement_rec', '0010_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='c',
            field=models.TextField(default=datetime.datetime(2016, 1, 10, 19, 29, 12, 994483, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
