# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_rec', '0011_post_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='c',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='logo',
        ),
    ]
