# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 13:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0013_auto_20160110_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 10, 13, 40, 32, 908933, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 10, 13, 40, 42, 779319, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
