# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0014_auto_20160110_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_events',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_highlights',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date_events',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date_highlights',
        ),
        migrations.RemoveField(
            model_name='post',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_events',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_highlights',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_events',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_highlights',
        ),
    ]
