# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20160108_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='infra_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/about_images'),
        ),
    ]
