# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20160109_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='infra_image',
            new_name='hod_image',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dept_history',
            new_name='hod_text',
        ),
        migrations.RemoveField(
            model_name='department',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='department',
            name='infra',
        ),
        migrations.RemoveField(
            model_name='department',
            name='labs',
        ),
    ]
