# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_auto_20160112_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='academic_cal',
            new_name='attachement',
        ),
    ]
